In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score



df = pd.read_csv("https://raw.githubusercontent.com/ShapeLab/ZooidsCompositePhysicalizations/refs/heads/master/Zooid_Vis/bin/data/student-dataset.csv")


print(df.shape)

(307, 16)

In [ ]:

df.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5

In [ ]:
df = df[['english.grade', 'math.grade', 'sciences.grade', 'language.grade']]

In [ ]:
df.head()

   english.grade  math.grade  sciences.grade  language.grade
0            3.5         3.7             3.1             1.0
1            2.9         3.2             3.6             5.0
2            3.9         3.8             3.2             5.0
3            3.3         2.8             3.2             5.0
4            3.7         2.6             3.4             1.0

In [ ]:
df.isnull().sum()

english.grade     0
math.grade        0
sciences.grade    0
language.grade    0
dtype: int64

In [ ]:

failing_threshold = 3


df['Pass/Fail'] = np.where((df['english.grade'] > failing_threshold) &
                            (df['math.grade'] > failing_threshold) &
                            (df['sciences.grade'] > failing_threshold) &
                            (df['language.grade'] > failing_threshold), 0, 1)

<ipython-input-6-772fde67b0c7>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Pass/Fail'] = np.where((df['english.grade'] > failing_threshold) &

In [ ]:
X = df.iloc[:, 0:-1]
Y = df['Pass/Fail']

print(X)
print(Y)

     english.grade  math.grade  sciences.grade  language.grade
0              3.5         3.7             3.1             1.0
1              2.9         3.2             3.6             5.0
2              3.9         3.8             3.2             5.0
3              3.3         2.8             3.2             5.0
4              3.7         2.6             3.4             1.0
..             ...         ...             ...             ...
302            3.6         3.7             3.1             5.0
303            3.6         3.9             4.0             5.0
304            3.2         3.4             3.9             5.0
305            3.0         2.8             2.9             5.0
306            3.8         3.2             4.0             5.0

[307 rows x 4 columns]
0      1
1      1
2      0
3      1
4      1
      ..
302    0
303    0
304    0
305    1
306    0
Name: Pass/Fail, Length: 307, dtype: int64

In [ ]:
df['Pass/Fail'].value_counts()

Pass/Fail
1    185
0    122
Name: count, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

precision = precision_score(y_test, y_pred)
print(f"Model Precision: {accuracy * 100:.2f}%")

recall = recall_score(y_test, y_pred)
print(f"Model Recall: {accuracy * 100:.2f}%")

Model Accuracy: 88.71%
Model Precision: 88.71%
Model Recall: 88.71%

In [ ]:
new_student_scores = pd.DataFrame([[ 5, 3, 3, 5]], columns=['english.grade', 'math.grade', 'sciences.grade', 'language.grade'])

prediction = model.predict(new_student_scores)

if prediction == 1:
    print("The student is predicted to Pass.")
else:
    print("The student is predicted to Fail.")

The student is predicted to Fail.